# Use Python 3.9 base image
FROM python:3.9

# Set working directory in the container
WORKDIR /app

# Copy the Python application file into the container
COPY app.py .

# Command to run the application
CMD ["python", "app.py"]
